---
- name: Converge
  hosts: all
  tasks:
    - name: Cria diretorio
      file:
        path: /usr/share/man/man1
        state: directory

    - name: "Include iac-role-services"
      include_role:
        name: "iac-role-services"
